name: "Semantic Release"

on:
  push:
    branches:
      - "main"

permissions:
  actions: write
  contents: write

jobs:
  changelog:
    name: "Python ${{ matrix.python-version }}"
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        python-version: ["3.14"]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # Version 7.0.1
        with:
          fetch-depth: 0

      - name: Bump version using semantic-release
        uses: python-semantic-release/python-semantic-release@b700dbeb1f431a0fcc30a79f3f0869407fe07278 # Version 10.7.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
