name: "Release"

on:
  release:
    types:
      - "published"
      - "prereleased"

env:
  COMPONENT_NAME: petkit

permissions: {}

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # Version 7.0.1

      - name: "Adjust version number"
        shell: bash
        run: |
          version="${{ github.event.release.tag_name }}"
          yq e -P -o=json \
            -i ".version = \"${version}\"" \
            "${{ github.workspace }}/custom_components/${{ env.COMPONENT_NAME }}/manifest.json"

      - name: "ZIP the integration directory"
        shell: "bash"
        run: |
          cd "${{ github.workspace }}/custom_components/${{ env.COMPONENT_NAME }}"
          zip ${{ env.COMPONENT_NAME }}.zip -r ./

      - name: "Upload the ZIP file to the release"
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # Version 3.0.2
        with:
          files: ${{ github.workspace }}/custom_components/${{ env.COMPONENT_NAME }}/${{ env.COMPONENT_NAME }}.zip
